services:
  containerpulse:
    build: .
    # Or use an image name if you push to a registry:
    # image: yourusername/containerpulse:latest
    container_name: containerpulse
    restart: unless-stopped
    ports:
      - "3000:3000"  # Web interface
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - containerpulse-data:/var/lib/containerpulse
      - containerpulse-logs:/var/log/containerpulse
      # Hot reloading volumes - read/write for development
      # - ./src:/app/src
      # - ./package.json:/app/package.json
      # - ./containerpulse-updater.sh:/usr/local/bin/containerpulse-updater.sh:ro      # Mount node_modules as volume to prevent conflicts
      # - /app/node_modules
    environment:
      - NODE_ENV=development
      - UPDATE_INTERVAL=300    # Check every 5 minutes in dev (in seconds)
      - LOG_LEVEL=debug        # Options: debug, info, warn, error
      - SESSION_SECRET=dev-session-secret-change-in-production
      - JWT_SECRET=dev-jwt-secret-change-in-production
      - WEBHOOK_SECRET=dev-webhook-secret
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=admin123  # Change this!
      - PORT=3000
    labels:
      - "auto-update=true"     # Self-updating
    # Enable tty for better logging output
    tty: true
    stdin_open: true

volumes:
  containerpulse-data:
  containerpulse-logs:
  node_modules:  # Named volume for node_modules to prevent conflicts with host
